export const BASKET_APPLY_PRODUCTS = 'BASKET_APPLY_PRODUCTS';

export const LAYOUT_APPLY_TITLE = 'LAYOUT_APPLY_TITLE';
export const LAYOUT_APPLY_H1 = 'LAYOUT_APPLY_H1';

export const PERSONAL_APPLY_PROFILE = 'PERSONAL_APPLY_PROFILE';
export const PERSONAL_APPLY_ORDERS = 'PERSONAL_APPLY_ORDERS';