export const BASKET_APPLY_PRODUCTS = 'BASKET_APPLY_PRODUCTS';
export const BASKET_APPLY_OLDPRODUCTS = 'BASKET_APPLY_OLDPRODUCTS';
export const CART_APPLY_VIEW_MODE = 'CART_APPLY_VIEW_MODE';

export const LAYOUT_APPLY_TITLE = 'LAYOUT_APPLY_TITLE';
export const LAYOUT_APPLY_H1 = 'LAYOUT_APPLY_H1';

export const PERSONAL_APPLY_PROFILE = 'PERSONAL_APPLY_PROFILE';
export const PERSONAL_APPLY_ORDERS = 'PERSONAL_APPLY_ORDERS';
export const PERSONAL_APPLY_FINANCE = 'PERSONAL_APPLY_FINANCE';
export const PERSONAL_ADDRESSES = 'PERSONAL_ADDRESSES';
export const PERSONAL_APPLY_MANAGER = 'PERSONAL_APPLY_MANAGER';
export const PERSONAL_APPLY_DISCOUNT = 'PERSONAL_APPLY_DISCOUNT';
export const PERSONAL_APPLY_CONTRACT = 'PERSONAL_APPLY_CONTRACT';
export const PERSONAL_APPLY_PETITIONS = 'PERSONAL_APPLY_PETITIONS';
export const PERSONAL_APPLY_FEEDS = 'PERSONAL_APPLY_FEEDS';

export const LISTING_APPLY_VIEW_MODE = 'LISTING_APPLY_VIEW_MODE';